CREATE TABLE admins (id INTEGER PRIMARY KEY, admin VARCHAR);
CREATE TABLE quotes (id INTEGER PRIMARY KEY, quote VARCHAR);
CREATE TABLE xingamentos (id INTEGER PRIMARY KEY, xinga VARCHAR);
CREATE TABLE mulheres (id INTEGER PRIMARY KEY, mulher VARCHAR);
